### ISSUE TITLE
Incorrect example code in documentation

### ISSUE THREAD

**Issue by detj** [csstree/csstree#163]
## Problem
The example code presented in [`reverse`](https://github.com/csstree/csstree/blob/master/docs/traversal.md#reverse) method of AST traversal is incorrect.

Here is the example code that is referred.

```js
const assert = require('assert');
const csstree = require('css-tree');
const ast = csstree.parse('.a { color: red; }');

const natural = [];
csstree.walk(ast, {
    enter(node) {
        natural.push(`enter ${node.type}`);
    },
    leave(node) {
        natural.push(`leave ${node.type}`);
    }
});

const reverse = [];
csstree.walk(ast, {
    reverse: true,    // !!!
    enter(node) {
        reverse.push(`enter ${node.type}`);
    },
    leave(node) {
        reverse.push(`leave ${node.type}`);
    }
});

// will pass assert
assert.deepEqual(
    reverse,
    natural.reverse()
);
```

The expectation is that the assertion should pass, while in actuality it fails. Here is the error message.

```
assert.js:118
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

[
  'enter StyleSheet',
  'enter Rule',
  'enter Block',
  'enter Declaration',
  'enter Value',
  'enter Identifier',
  'leave Identifier',
  'leave Value',
  'leave Declaration',
  'leave Block',
  'enter SelectorList',
  'enter Selector',
  'enter ClassSelector',
  'leave ClassSelector',
  'leave Selector',
  'leave SelectorList',
  'leave Rule',
  'leave StyleSheet'
]

should loosely deep-equal

[
  'leave StyleSheet',
  'leave Rule',
  'leave Block',
  'leave Declaration',
  'leave Value',
  'leave Identifier',
  'enter Identifier',
  'enter Value',
  'enter Declaration',
  'enter Block',
  'leave SelectorList',
  'leave Selector',
  'leave ClassSelector',
  'enter ClassSelector',
  'enter Selector',
  'enter SelectorList',
  'enter Rule',
  'enter StyleSheet'
]
    at Object.<anonymous> (/private/tmp/css-tree-try/index.js:27:8)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: [
    'enter StyleSheet',    'enter Rule',
    'enter Block',         'enter Declaration',
    'enter Value',         'enter Identifier',
    'leave Identifier',    'leave Value',
    'leave Declaration',   'leave Block',
    'enter SelectorList',  'enter Selector',
    'enter ClassSelector', 'leave ClassSelector',
    'leave Selector',      'leave SelectorList',
    'leave Rule',          'leave StyleSheet'
  ],
  expected: [
    'leave StyleSheet',    'leave Rule',
    'leave Block',         'leave Declaration',
    'leave Value',         'leave Identifier',
    'enter Identifier',    'enter Value',
    'enter Declaration',   'enter Block',
    'leave SelectorList',  'leave Selector',
    'leave ClassSelector', 'enter ClassSelector',
    'enter Selector',      'enter SelectorList',
    'enter Rule',          'enter StyleSheet'
  ],
  operator: 'deepEqual'
}
```

## Solution

Not sure what should be updated. But clearly, either the docs or the code needs to change to reflect the correct behavior.

## Environment details

```
css-tree@1.1.3
node@14.17.1
```

**Comment by lazarljubenovic** [comment]
Seems like the docs/test was written in haste. It doesn't make sense to literally reverse the order of each enter/leave as a separate entity. You cannot start the traversal by leaving the outermost node.

**Comment by lahmatiy** [comment]
In the beginning the `revert` option swapped the order of calling the "enter" and "leave" handlers. This behaved like `natural.reverse()` in some cases so the example was correct. However, that's was not always true. Plus it was a little weird and not very practical, but an implementation was quite simple.
The turning point in behaviour change was the introduction of `break` and `skip` features. So implementation was changed to always call `enter` handler first then `leave` handler regardless of the traversal order. But as you noticed, the example has not been updated. It is now fixed to reflect the current behaviour.
