### ISSUE TITLE
`10 % 1` Modulo Doesn't Parse

### ISSUE THREAD

**Issue by shellscape** [csstree/csstree#195]
Doesn't appear that the lib supports the modulo operator yet, or at least not in the raw context:

```js
import { parse, walk } from 'css-tree';

const value = '10 % 1';
const ast = parse(value, { context: 'value', positions: true });

console.log(ast.children.toArray());
```

yields:

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^
SyntaxError: Unexpected input
    at TokenStream.error (file:///Users/code/ebnf/node_modules/.pnpm/css-tree@2.1.0/node_modules/css-tree/lib/parser/create.js:282:19)
    at parse (file:///Users/code/ebnf/node_modules/.pnpm/css-tree@2.1.0/node_modules/css-tree/lib/parser/create.js:336:20)
    at file:///Users/code/ebnf/index.mjs:6:13
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12) {
  source: '10 % 1',
  offset: 3,
  line: 1,
  column: 4,
  sourceFragment: [Function: sourceFragment],
  formattedMessage: 'Parse error: Unexpected input\n    1 |10 % 1\n----------^'
}
```

Tried changing that to `calc(10 % 1)` and it got angry with:

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^
SyntaxError: ")" is expected
    at TokenStream.error (file:///Users/code/ebnf/node_modules/.pnpm/css-tree@2.1.0/node_modules/css-tree/lib/parser/create.js:282:19)
    at TokenStream.eat (file:///Users/code/ebnf/node_modules/.pnpm/css-tree@2.1.0/node_modules/css-tree/lib/parser/create.js:230:22)
    at TokenStream.parse [as Function] (file:///Users/code/ebnf/node_modules/.pnpm/css-tree@2.1.0/node_modules/css-tree/lib/syntax/node/Function.js:26:14)
    at TokenStream.defaultRecognizer (file:///Users/code/ebnf/node_modules/.pnpm/css-tree@2.1.0/node_modules/css-tree/lib/syntax/scope/default.js:52:24)
    at TokenStream.readSequence (file:///Users/code/ebnf/node_modules/.pnpm/css-tree@2.1.0/node_modules/css-tree/lib/parser/sequence.js:22:40)
    at TokenStream.parse [as Value] (file:///Users/code/ebnf/node_modules/.pnpm/css-tree@2.1.0/node_modules/css-tree/lib/syntax/node/Value.js:8:27)
    at TokenStream.<anonymous> (file:///Users/code/ebnf/node_modules/.pnpm/css-tree@2.1.0/node_modules/css-tree/lib/parser/create.js:34:26)
    at parse (file:///Users/code/ebnf/node_modules/.pnpm/css-tree@2.1.0/node_modules/css-tree/lib/parser/create.js:333:45) {
  source: 'calc(10 % 1)',
  offset: 8,
  line: 1,
  column: 9,
  sourceFragment: [Function: sourceFragment],
  formattedMessage: 'Parse error: ")" is expected\n    1 |calc(10 % 1)\n---------------^'
}
```

**Comment by shellscape** [comment]
Ah this was IE-only and is no longer spec-compliant https://www.w3.org/TR/css3-values/#calc-notation
