### ISSUE TITLE
Test & build not working on Windows

### ISSUE THREAD

**Issue by scripthunter7** [csstree/csstree#229]
```
E:\csstree>npm run test

> css-tree@2.3.1 test
> mocha lib/__tests --reporter ${REPORTER:-progress}


× ERROR: TypeError: Could not load reporter "${REPORTER:-progress}":

 Error: Cannot find module 'E:\csstree\${REPORTER:-progress}'
Require stack:
- E:\csstree\node_modules\mocha\lib\cli\run-helpers.js
- E:\csstree\node_modules\mocha\lib\cli\options.js
- E:\csstree\node_modules\mocha\bin\mocha
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at exports.validateLegacyPlugin (E:\csstree\node_modules\mocha\lib\cli\run-helpers.js:237:25)
    at E:\csstree\node_modules\mocha\lib\cli\run.js:354:9 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\csstree\\node_modules\\mocha\\lib\\cli\\run-helpers.js',
    'E:\\csstree\\node_modules\\mocha\\lib\\cli\\options.js',
    'E:\\csstree\\node_modules\\mocha\\bin\\mocha'
  ]
}
    at createInvalidReporterError (E:\csstree\node_modules\mocha\lib\errors.js:207:13)
    at createInvalidLegacyPluginError (E:\csstree\node_modules\mocha\lib\errors.js:341:14)
    at createUnknownError (E:\csstree\node_modules\mocha\lib\cli\run-helpers.js:220:5)
    at exports.validateLegacyPlugin (E:\csstree\node_modules\mocha\lib\cli\run-helpers.js:239:15)
    at E:\csstree\node_modules\mocha\lib\cli\run.js:354:9 {
  code: 'ERR_MOCHA_INVALID_REPORTER',
  reporter: '${REPORTER:-progress}'
}
```

```
E:\csstree>npm run build

> css-tree@2.3.1 build
> npm run bundle && npm run esm-to-cjs --


> css-tree@2.3.1 bundle
> node scripts/bundle

E:\csstree\node_modules\esbuild\lib\main.js:1356
        return callback(new Error(error), null);
                        ^

Error: [replace] "onLoad" filter is not a valid Go regular expression: "(E:\\csstree\\lib\\data\\.js|E:\\csstree\\lib\\data\\.cjs|E:\\csstree\\lib\\version\\.js|E:\\csstree\\lib\\version\\.cjs)$"
    at E:\csstree\node_modules\esbuild\lib\main.js:1356:25
    at E:\csstree\node_modules\esbuild\lib\main.js:678:9
    at handleIncomingPacket (E:\csstree\node_modules\esbuild\lib\main.js:773:9)
    at Socket.readFromStdout (E:\csstree\node_modules\esbuild\lib\main.js:644:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by lahmatiy** [comment]
Fixed by https://github.com/csstree/csstree/commit/41e70a638f77644acea89d6edb90ed535d416309
