### ISSUE TITLE
Imported Object.prototype conflict with csstree module!

### ISSUE THREAD

**Issue by Nevro** [csstree/csstree#262]
testImport.js
```javascript
Object.prototype.testProtoFunc = function () {
	//code
	return this;
};
```
main.js
```javascript
import * as testImport from './testImport.js';
import * as csstree from 'css-tree';

csstree.parse('@example 1 2;', {
    parseAtrulePrelude: false
});
```
Output:
```
file:///home/user/test/node_modules/css-tree/lib/data.js:27
            prelude: atrule.syntax.trim().replace(/\{(.|\s)+\}/, '').match(/^@\S+\s+([^;\{]*)/)[1].trim() || null,
                                   ^

TypeError: Cannot read properties of undefined (reading 'trim')
    at preprocessAtrules (file:///home/user/test/node_modules/css-tree/lib/data.js:27:36)
    at file:///home/user/test/node_modules/css-tree/lib/data.js:95:27
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.5.0
csstree v2.3.1
```
Cause problem only if prototype is imported from external file.

**Comment by Nevro** [comment]
Tested! Now behaves as expected!
