### ISSUE TITLE
csstree.fromPlainObject - Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by strarsis** [csstree/csstree#66]
@lahmatiy: Apparently some code in `css-tree` hadn't been adjusted yet to 
the change to `prelude` in version `1.0.0-alpha25`.

Standalone code for reproducing the issue (derived from https://github.com/strarsis/svgo/blob/6964351c1a9ca3977446ad4574ce24e378b23827/plugins/chainFilters.js#L123):
```js
'use strict';

var csstree = require('css-tree');

var filterClassRuleObj = {
            type: 'Rule', 
            selector: {
                type: 'SelectorList',
                children: [
                    {
                        type: 'Selector', 
                        children: [
                            {
                                type: 'ClassSelector',
                                name: 'test'
                            }
                        ]
                    }
                ]
            },
            block: {
                type: 'Block',
                children: [
                    {
                        type: 'Declaration',
                        important: false,
                        property: 'filter',
                        value: {
                            type: 'Value',
                            children: [
                                {
                                    type: 'String',
                                    value: '"url(' + '#' + 'test' + ')"'
                                }
                            ]
                        }
                    }
                ]
            }
        };

csstree.fromPlainObject(filterClassRuleObj)

````

When running the code with `css-tree` version `1.0.0-alpha25` installed:
````
[...]svgo/node_modules/css-tree/lib/convertor/create.js:10
                if (node.children && node.children instanceof List === false) {
                        ^

TypeError: Cannot read property 'children' of undefined
    at Object.fn ([...]svgo/node_modules/css-tree/lib/convertor/create.js:10:25)
    at walk ([...]svgo/node_modules/css-tree/lib/walker/create.js:256:20)
    at Object.eval (eval at createWalker ([...]svgo/node_modules/css-tree/lib/walker/create.js:235:29), <anonymous>:5:1)
    at walk ([...]svgo/node_modules/css-tree/lib/walker/create.js:258:39)
    at walk ([...]svgo/node_modules/css-tree/lib/walker/create.js:264:13)
    at Object.fromPlainObject ([...]svgo/node_modules/css-tree/lib/convertor/create.js:9:13)
    at Object.<anonymous> ([...]svgo/plugins/test.js:42:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
````

**Comment by lahmatiy** [comment]
`Rule.selector` was renamed to `Rule.prelude` in [alpha24](https://github.com/csstree/csstree/releases/tag/v1.0.0-alpha24). Just rename `selector` to `prelude` at [line 125](https://github.com/strarsis/svgo/blob/6964351c1a9ca3977446ad4574ce24e378b23827/plugins/chainFilters.js#L125)

**Comment by strarsis** [comment]
This fixed it.
