### ISSUE TITLE
TypeError: node.children.each is not a function

### ISSUE THREAD

**Issue by stereobooster** [csstree/csstree#68]
```
TypeError: node.children.each is not a function
    at Object.eval [as StyleSheet] (eval at createWalker (/minimalcss/node_modules/css-tree/lib/walker/create.js:235:29), <anonymous>:5:15)
    at walk (/minimalcss/node_modules/css-tree/lib/walker/create.js:258:39)
    at Object.walk (/minimalcss/node_modules/css-tree/lib/walker/create.js:264:13)
    at response.text.then.text (/minimalcss/src/run.js:86:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

This is the code that triggers it

```js
const ast = csstree.parse(text, {
  parseValue: true,
  parseRulePrelude: false
})
stylesheetAstObjects[responseUrl] = csstree.toPlainObject(ast)
csstree.walk(stylesheetAstObjects[responseUrl], (node) => {})
```

Reproduction example is here https://github.com/peterbe/minimalcss/pull/28

There is an array in one place, while code always expects Lists
```diff
    for (var name in types) {
        if (hasOwnProperty.call(types, name)) {
            var config = types[name];
            walkers[name] = Function('node', 'context', 'walk',
                (config.context ? 'var old = context.' + config.context + ';\ncontext.' + config.context + ' = node;\n' : '') +
                config.fields.map(function(field) {
                    var line = field.type === 'list'
-                        ? 'node.' + field.name + '.each(walk);'
+                        ? 'node.' + field.name + '.forEach ? node.' + field.name + '.forEach(walk) : node.' + field.name + '.each(walk);'
                        : 'walk(node.' + field.name + ');';

                    if (field.nullable) {
                        line = 'if (node.' + field.name + ') {\n    ' + line + '}';
                    }

                    return line;
                }).join('\n') +
                (config.context ? '\ncontext.' + config.context + ' = old;' : '')
            );
        }
    }
```

**Comment by lahmatiy** [comment]
That's correct. CSSTree's AST uses List instead of array, since it's better for most cases especially when needs to mutate a list.
We can add a `forEach` method to List class and replace `each` for `forEach` everywhere – most code even would work. But `List#each()` and `Array#forEach()` have a different arguments. I'm afraid it will confuse more than current issue. Need to think about it...

I have a single question, why do you convert AST to a "plain object"? (actually it converts Lists to arrays)

**Comment by stereobooster** [comment]
> I have a single question, why do you convert AST to a "plain object"? (actually it converts Lists to arrays)

this gives the same error

```js
const ast = csstree.parse(text, {
  parseValue: true,
  parseRulePrelude: false
})
csstree.walk(ast, (node) => {})
```

**Comment by lahmatiy** [comment]
Last one is really strange, it shouldn't fails.
Can I get a CSS which produce an error?

**Comment by stereobooster** [comment]
```css
body { background: url(small.jpg); }
p { background-image: url("small.jpg"); }

img { border: 1px solid #ccc; }
p { color: maroon; }
ol, li { color: blue; }
li, p { text-style: italic; }
```

**Comment by lahmatiy** [comment]
Have no any exceptions, tried that code:
```js
const csstree = require('css-tree');
const css = `
body { background: url(small.jpg); }
p { background-image: url("small.jpg"); }

img { border: 1px solid #ccc; }
p { color: maroon; }
ol, li { color: blue; }
li, p { text-style: italic; }
`;

const ast = csstree.parse(css, {
  parseValue: true,
  parseRulePrelude: false
});
csstree.walk(ast, (node) => {})

console.log(JSON.stringify(ast, null, 2));
```

**Comment by stereobooster** [comment]
yes standalone version works for me too.

...

fixed it by changing order of rows :/

```diff
const ast = csstree.parse(text, {
  parseValue: true,
  parseRulePrelude: false
})
- stylesheetAstObjects[responseUrl] = csstree.toPlainObject(ast)
csstree.walk(ast, (node) => {})
+ stylesheetAstObjects[responseUrl] = csstree.toPlainObject(ast)
```
