### ISSUE TITLE
confused about `atrulePrelude` context

### ISSUE THREAD

**Issue by olsonpm** [csstree/csstree#82]
When I parse the following

```css
@media (min-width: 500px) {
  body {
    background-color: blue;
  }
}
```

The AtrulePrelude is expectedly: `(min-width: 500px)`

But if I parse that text alone with `context: 'atrulePrelude'` e.g.

```js
const ast = cssTree.parse('(min-width: 500px)', { context: 'atrulePrelude' })
```

Then I receive the error 

<details>
  <summary>error</summary>
  <pre>
CssSyntaxError: RightParenthesis is expected
    at Tokenizer.error (.../node_modules/css-tree/lib/tokenizer/Tokenizer.js:587:15)
    at Tokenizer.eat (.../node_modules/css-tree/lib/tokenizer/Tokenizer.js:509:18)
    at Object.parse [as Parentheses] (.../node_modules/css-tree/lib/syntax/node/Parentheses.js:19:26)
    at Object.defaultRecognizer (.../node_modules/css-tree/lib/syntax/scope/default.js:38:25)
    at Object.readSequence (.../node_modules/css-tree/lib/parser/sequence.js:32:36)
    at Object.parse [as AtrulePrelude] (.../node_modules/css-tree/lib/syntax/node/AtrulePrelude.js:26:29)
    at Object.atrulePrelude (.../node_modules/css-tree/lib/syntax/config/parser.js:7:25)
    at Object.parse (.../node_modules/css-tree/lib/parser/create.js:169:39)
  </pre>
</details>
<br>

I logged the current token when it receives that error, it happens on the colon.
```txt
(min-width: 500px)
          ^
```

It works fine if I parse using `context: 'mediaQueryList'`, but I was wondering why atrulePrelude doesn't work.

Thanks for this library, I'm learning a lot.

**Comment by lahmatiy** [comment]
@olsonpm You need to specify a at-rule, because prelude parse rules depends on it.

```
const ast = cssTree.parse('(min-width: 500px)', {
    context: 'atrulePrelude',
    atrule: 'media'
})
```

**Comment by olsonpm** [comment]
Sorry for missing that.  Works great.
