### ISSUE TITLE
Need to upgrade mdn-data to 2.0.1

### ISSUE THREAD

**Issue by acconrad** [csstree/csstree#94]
[MDN/Data](https://github.com/mdn/data) updated their license in 2.0 to use a better open source license that doesn't break licensing issues for enterprise companies.

Unfortunately this change breaks the build and I'm not too familiar with the project to really dive in:

```bash
Write data to /Code/csstree/dist/default-syntax.json

/Code/csstree/lib/lexer/grammar/tokenizer.js:51
        throw new SyntaxParseError(message, this.str, this.pos);
        ^
SyntaxParseError: Expect `&`
    at Tokenizer.error (/Code/csstree/lib/lexer/grammar/tokenizer.js:51:15)
    at Tokenizer.eat (/Code/csstree/lib/lexer/grammar/tokenizer.js:42:18)
    at peek (/Code/csstree/lib/lexer/grammar/parse.js:415:23)
    at readImplicitGroup (/Code/csstree/lib/lexer/grammar/parse.js:327:20)
    at parse (/Code/csstree/lib/lexer/grammar/parse.js:483:18)
    at Object.get [as syntax] (/Code/csstree/lib/lexer/Lexer.js:157:36)
    at dumpMapSyntax (/Code/csstree/lib/lexer/Lexer.js:21:23)
    at Lexer.dump (/Code/csstree/lib/lexer/Lexer.js:317:25)
npm ERR! code ELIFECYCLE
```

**Comment by lahmatiy** [comment]
Looks like mdn/data has some errors in syntaxes. I'm going to update mdn/data version and fixing it soon.

**Comment by lahmatiy** [comment]
Bad syntaxes were removed in commit https://github.com/mdn/data/commit/0808be012bae5ea8554ae209f24a68c9dc902970 – so we need await for release of a new version.
Or add something like this to `patch.json`:
```json
    "motion": { "syntax": null },
    "motion-offset": { "syntax": null },
    "motion-path": { "syntax": null },
    "motion-rotation": { "syntax": null },
```

**Comment by acconrad** [comment]
@lahmatiy all set https://github.com/csstree/csstree/pull/95
